version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=production
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
